version: '2'
services:
  dockerbeat:
    image: ingensi/dockerbeat:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./dockerbeat:/etc/dockerbeat
    links:
     - elasticsearch
