version: '2'
services:
  kibana:
    image: kibana:5
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5601:5601"
    links:
     - elasticsearch
  logstash:
    image: logstash:2.4
    environment:
     - LS_JAVA_OPTS=-Xms512m -Xmx512m
    command: -f /config/logstash.conf
    volumes:
     - ./logstash:/config
    ports:
     - "5999:5999"
     - "5999:5999/udp"
    links:
     - elasticsearch
  elasticsearch:
    image: elasticsearch:5
    environment:
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
     - "9200:9200"
    volumes:
     - ./elasticsearch/config:/usr/share/elasticsearch/config
     - ./elasticsearch/data:/usr/share/elasticsearch/data
